### ISSUE TITLE
Fehler beim Kompelilieren

### ISSUE THREAD

**Issue by chris3600410** [nikolaus-lueneburg/I2CWLANGateway#1]
Hallo bekommen beim Kompillieren des sketches folgendende fehlermeldung

Arduino: 1.8.13 (Windows 10), Board: "WeMos D1 R1, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

C:\Users\chris\Documents\Arduino\I2CWLANGateway\I2CWLANGateway.ino: In function 'void setup()':

I2CWLANGateway:75:7: error: 'enableStaticIP' was not declared in this scope

   if (enableStaticIP)

       ^

I2CWLANGateway:85:8: error: 'enableStaticIP' was not declared in this scope

   if (!enableStaticIP)

        ^

exit status 1

'enableStaticIP' was not declared in this scope

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by nikolaus-lueneburg** [comment]
Hallo chris8519,
in der configuration.h wird in Zeile 20 die Bool Variable EnableStaticIP gesetzt. Ich denke die Variable ist fehlerhaft / fehlt komplett oder die configuration.h wird nicht geladen. Könntest du das bitte einmal prüfen? Danke!
Viele Grüße
Stefan
